
public interface Message {
	public enum MessageType{
		REGISTER_REQUEST,
		REGISTER_RESPONSE,
		DEREGISTER_REQUEST,
		MESSAGING_NODES_LIST,
		LINK_WEIGHTS,
		TASK_INITIATE,
		TASK_COMPLETE,
		PULL_TRAFFIC_SUMMARY,
		TRAFFIC_SUMMARY
	}
}
